name: Build Starting..

on: 
  #releasepush:
    #pushbuild

  watch: 
      types: [started]
env:
  ROM_URL: https://mirrors.lolinet.com/firmware/lenovo/l10041/official/L10041_ROW_SECURE_USER_M6750m_Q_DRV_11.5.263_ST_200824_SVC.zip
  ROM_NAME: ZUI
  FIRMWAREZIPNAME: ZUI_Test.zip
  ZIP_NAME: ZUI
  SCRIPT_NAME: ZUIDP
  TZ: Europe/London
  SFDIRA1: cd /home/pfs/project/berkay-gsi/ZUI
  SFDIRA2: cd /home/pfs/project/berkay-gsi/berkay
  SFUSER: ${{ secrets.SFUSER }}
  SECRETS_PASSWORD: ${{ secrets.SFGPASS }}
  MIR: wet
  
jobs:
    build:
       runs-on: ubuntu-latest

    
       steps:
        - name: Checkout
          uses: actions/checkout@main
       
           
        - name: Setting up the SPICES and its SPICES
          run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk wget
            sudo -E apt-get -qq install python3
            sudo -E apt-get -qq install simg2img
            sudo apt-get install -y expect
            git clone "https://github.com/amyGSI/AmyBakerTools" ErfanGSIs
            sudo chmod -R 777 ErfanGSIs
            cd ErfanGSIs
            sudo bash setup.sh 
            
        - name: DOWNLOADING THE FIRMWARE
          run: cd ErfanGSIs && sudo wget $ROM_URL 
          
        - name: GENERATION OF BAKED GOODIES
          run: | 
            cd ErfanGSIs && sudo ./$SCRIPT_NAME.sh $ROM_NAME $FIRMWAREZIPNAME && sudo umount system && sudo rm -rf system
            
            
        - name: MOUNTING THE SYSTEM
          run: cd ErfanGSIs/cache && sudo mkdir dynamic && sudo mount -o ro system.img dynamic 
         
        - name: MAKING THE COOKIES
          run: cd ErfanGSIs && sudo ./url2GSI.sh cache/dynamic $ROM_NAME  
       
        - name: Zipping
          run: |
              mkdir final
              sudo chmod -R 777 ErfanGSIs/output
              zip -r ErfanGSIs/output/$ZIP_NAME-GSI-Aonly.7z ErfanGSIs/output/*-Aonly-*.img 
              zip -r ErfanGSIs/output/$ZIP_NAME-GSI-AB.7z ErfanGSIs/output/*-AB-*.img
              
                
        - name: Uploading SourceForge
          run: |   
              cd ErfanGSIs/output
              expect -c " 
              spawn sftp berkay-gsi@frs.sourceforge.net
              expect \"yes/no\"
              send \"yes\r\"
              expect \"Password\"        
              send \"${{ secrets.SFGPASS }}\r\"
              expect \"sftp> \"
              send \"$SFDIRA2\r\"
              set timeout -1
              send \"put *-Aonly-*.txt\r\"
              expect \"Uploading\"
              expect \"100%\"
              expect \"sftp>\"
              interact"
              expect -c "
              spawn sftp berkay-gsi@frs.sourceforge.net
              expect \"Password\"
              send \"${{ secrets.SFGPASS }}\r\"
              expect \"sftp> \"
              send \"$SFDIRA1\r\"
              set timeout -1
              send \"put $ZIP_NAME-GSI-Aonly.7z\r\"
              expect \"Uploading\"
              expect \"100%\"
              expect \"sftp>\"
              interact"
              expect -c "
              spawn sftp berkay-gsi@frs.sourceforge.net
              expect \"Password\"
              send \"${{ secrets.SFGPASS }}\r\"
              expect \"sftp> \"
              send \"$SFDIRA1\r\"
              set timeout -1
              send \"put $ZIP_NAME-GSI-AB.7z\r\"
              expect \"Uploading\"
              expect \"100%\"
              expect \"sftp>\"
              send \"bye\r\"
              interact"
              
        - name: uploading to Wetransfer
          run: |   
              cd ErfanGSIs/output   
              curl -sL https://git.io/file-transfer | sh    
              ./transfer $MIR "$ZIP_NAME-GSI-Aonly.7z" | grep -o -P '(?<=Download Link: )\S+')
              ./transfer $MIR "$ZIP_NAME-GSI-AB.7z" | grep -o -P '(?<=Download Link: )\S+') 
                
        - name: Print build info
          run: |
              cat ErfanGSIs/output/*-Aonly-*.txt
